sonar.projectKey=yvanvds_DoThing
sonar.organization=yvanvds

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=DoThing
#sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=lib
sonar.tests=test
sonar.exclusions=smartschool-researcher-mcp/**
sonar.test.exclusions=smartschool-researcher-mcp/**

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
sonar.objc.file.suffixes=-

sonar.dart.lcov.reportPaths=coverage/lcov.info
