name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: windows-latest
    defaults:
      run:
        working-directory: do_thing
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
          
      # The analysis requires to retrieve dependencies and build successfully
      - name: Setup Flutter
        env:
          FLUTTER_SHA: 8bf2090718fea3655f466049a757f823898f0ad1 # replace with a real Flutter commit
        run: |
          git init "$env:RUNNER_TEMP\flutter"
          git -C "$env:RUNNER_TEMP\flutter" remote add origin https://github.com/flutter/flutter.git
          git -C "$env:RUNNER_TEMP\flutter" fetch --depth 1 origin $env:FLUTTER_SHA
          git -C "$env:RUNNER_TEMP\flutter" checkout --detach $env:FLUTTER_SHA
          "$env:RUNNER_TEMP\flutter\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Test with coverage
        run: flutter test --coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}